#!/usr/bin/env python3
"""Audit placeholder and missing data across CSV files.

This report is intentionally non-failing by default. It helps decide what to fix
next without blocking useful draft data.

Output:
  docs/MISSING_DATA_REPORT.md
"""

from __future__ import annotations

import csv
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
OUT_PATH = ROOT / "docs" / "MISSING_DATA_REPORT.md"
PLACEHOLDER_RE = re.compile(
    r"\b(needs_source|needs_review|needs_specific|unknown|verify|confirm|placeholder|not_started|draft_source_needed)\b",
    re.IGNORECASE,
)


def stringify(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, list):
        return " ".join(str(item) for item in value if item is not None)
    return str(value)


def iter_csv_rows():
    for path in sorted(DATA_DIR.rglob("*.csv")):
        if "generated" in path.parts:
            continue
        with path.open(newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for line_no, row in enumerate(reader, start=2):
                yield path, line_no, row


def main() -> int:
    findings: list[tuple[str, int, str, str]] = []
    status_counts: Counter[str] = Counter()
    file_counts: Counter[str] = Counter()
    missing_required: dict[str, list[str]] = defaultdict(list)

    for path, line_no, row in iter_csv_rows():
        rel = str(path.relative_to(ROOT))
        review_status = stringify(row.get("review_status")).strip()
        if review_status:
            status_counts[review_status] += 1
        if review_status in {"needs_source", "needs_review"}:
            findings.append((rel, line_no, "review_status", review_status))
            file_counts[rel] += 1

        for key, raw_value in row.items():
            value = stringify(raw_value)
            column = stringify(key) or "extra_columns"
            if PLACEHOLDER_RE.search(value):
                findings.append((rel, line_no, column, value[:160]))
                file_counts[rel] += 1

        if "ingredient_id" in row and not stringify(row.get("ingredient_id")).strip():
            missing_required[rel].append(f"line {line_no}: ingredient_id")
        if "canonical_name" in row and not stringify(row.get("canonical_name")).strip():
            missing_required[rel].append(f"line {line_no}: canonical_name")
        if review_status == "reviewed" and "citation_id" in row and not stringify(row.get("citation_id")).strip():
            missing_required[rel].append(f"line {line_no}: reviewed row missing citation_id")

    lines = [
        "# Missing Data Report",
        "",
        "Generated by `scripts/audit_missing_data.py`.",
        "",
        "## Review-status counts",
        "",
        "| Status | Count |",
        "|---|---:|",
    ]
    for status, count in status_counts.most_common():
        lines.append(f"| {status} | {count} |")

    lines.extend(["", "## Files with placeholder signals", "", "| File | Signals |", "|---|---:|"])
    for file_name, count in file_counts.most_common():
        lines.append(f"| {file_name} | {count} |")

    lines.extend(["", "## Missing required fields", ""])
    if missing_required:
        for file_name, items in sorted(missing_required.items()):
            lines.append(f"### {file_name}")
            for item in items[:100]:
                lines.append(f"- {item}")
            if len(items) > 100:
                lines.append(f"- ... {len(items) - 100} more")
            lines.append("")
    else:
        lines.append("No missing required fields found by this audit.")

    lines.extend(["", "## Top placeholder rows", "", "| File | Line | Column | Value |", "|---|---:|---|---|"])
    for rel, line_no, key, value in findings[:300]:
        safe_value = value.replace("|", "/")
        lines.append(f"| {rel} | {line_no} | {key} | {safe_value} |")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
